newchanges
limanmys/liman-ansible pull request #11
Opened 2021-12-27 12:08 UTC by susalihh

+playbook2 özelliği eklendi,
+dosya düzenleme aktifleştirildi

2022-01-05 13:03 UTC, susalihh commented
pullandrequest2

2022-01-07 13:42 UTC, dogukanoksuz requested changes
Gerekli değişiklikler yapılıp testleri gerçekleştirildikten sonra master'a merge edilebilir.

2022-01-07 13:42 UTC, dogukanoksuz commented on app/Controllers/FileController.php
> +		$filePath = request('filePath');
Ekstra tanımlama yapmak yerine 21. satırda direkt $filePath yerine request("filePath") yazılabilir.

2022-01-07 13:42 UTC, dogukanoksuz commented on app/Controllers/HostsController.php
> +		/*$arrayHosts = yaml_parse($textHostFile)['all']['children'];
Master branchına çıkılacak kodlarda açıklama satırları bulunmamalıdır.

2022-01-07 13:42 UTC, dogukanoksuz commented on app/Controllers/LogController.php
> +		$output = Command::runSudo('cat /var/playbook-logs/{:fileName}', [
62. satırda bulunan $fileName yerine request("fileName") yazılabilir.

2022-01-07 13:42 UTC, dogukanoksuz commented on app/Controllers/PlaybookController.php
> +		if($output!="")
if (empty($output)) kullanılması daha doğru ve anlaşılır olacaktır.

2022-01-07 13:42 UTC, dogukanoksuz commented on app/Controllers/PlaybookController.php
> +		if ($checkDirectory == '1') {
if ((bool) $checkDirectory) olarak tanımlanabilir.

2022-01-07 13:42 UTC, dogukanoksuz commented on app/Controllers/PlaybookController.php
> +		$output = Command::runSudo('cat /var/playbooks/{:fileName} | base64', [
$fileName yerine request("fileName") kullanılabilir.

2022-01-07 13:42 UTC, dogukanoksuz commented on app/Controllers/PlaybookController.php
> +			'fileName' => $fileName
$fileName yerine request("fileName") kullanılabilir.

2022-01-07 13:42 UTC, dogukanoksuz commented on app/Controllers/PlaybookController.php
> +		if (trim($result) == '') {
if (empty(trim($result)) olarak kullanılabilir

2022-01-07 13:42 UTC, dogukanoksuz commented on app/Controllers/PlaybookController.php
> +		if($textArea != ""){
empty($textArea) olarak değiştirilebilir

2022-01-07 13:42 UTC, dogukanoksuz commented on app/Controllers/PlaybookController.php
> +		if ($checkFile == '1') {
if ((bool) $checkFile)

2022-01-07 13:42 UTC, dogukanoksuz commented on app/Controllers/PlaybookController.php
> +		if ($checkDirectory == '0') {
if ((bool) !$checkDirectory) olarak değiştirilebilir

2022-01-07 13:42 UTC, dogukanoksuz commented on routes.php
> +    "get_Output" => "PlaybookController@getOutput",
get_Output yerine get_output olarak değişiklik yapılabilir

2022-01-07 13:42 UTC, dogukanoksuz commented on views/pages/files.blade.php
> +        var filePath = data2.node.id;
var yerine let kullanımı yapılmalıdır. var global scopeda değişken tanımlamaktadır ve fonksiyon scopeda tanımlama yapılmaması verinin doğru gitmeme ihtimalini doğurabilir.

2022-01-07 13:42 UTC, dogukanoksuz commented on views/pages/logs.blade.php
> +            $('#logTable2').html(response).find('table').DataTable(dataTablePresets('normal'));
#logTable2 tanımlaması ve bu şekilde 2 içeren kısımlar normal isimlere çevirilmelidir.

2022-01-07 13:42 UTC, dogukanoksuz commented on views/pages/logs.blade.php
> +                let fileName = line.querySelector("#name").innerHTML + "-.-" + line.querySelector("#user").innerHTML;
line.find("#name").html() olarak jQuery ile değiştirileblir. Bu şekildeki değişiklikleri kod geneli de yapabilirsin. Uzunca yazmana gerek yok.

2022-01-11 14:50 UTC, merged